sylius_refund_shop_api_customer_show_refund_requests:
    path: /me/refund-requests
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.show_shop_user_refund_request_list

sylius_refund_shop_api_show_shop_user_refund_request_by_id:
    path: /me/refund-request/{id}
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.show_shop_user_refund_request_by_id

sylius_refund_shop_api_show_shop_user_refund_request_message_list:
    path: /me/refund-request/{id}/messages
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.show_shop_user_refund_request_message_list

sylius_refund_shop_api_add_shop_user_refund_request_message:
    path: /me/refund-request/{id}/send-message
    methods: [POST]
    defaults:
        _controller: sylius_refund_plugin.controller.api.add_refund_request_message_action

sylius_refund_shop_api_get_refund_request_message_file:
    path: /me/refund-request/message-file/{hash}
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.get_refund_request_message_file_action
