sylius_refund_shop_api_customer_show_refund_requests:
    path: /me/refund-requests
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.show_shop_user_refund_request_list

sylius_refund_shop_api_show_shop_user_refund_request_by_id:
    path: /me/refund-request/{id}
    methods: [GET]
    defaults:
        _controller: sylius_refund_plugin.controller.api.show_shop_user_refund_request_by_id
